# Generated by Django 5.2.7 on 2025-10-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('cantidad', models.IntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
